name: counter_app
description: A simple counter with persistence

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: '>=3.7.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.13.0
  firebase_auth: ^5.1.1
  shared_preferences: ^2.2.2
  cloud_firestore: ^5.5.0 

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
