
name: firebase_web_auth
description: Firebase Auth Web Example

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.24.0
  firebase_auth: ^4.17.4
  provider: ^6.1.2

flutter:
  uses-material-design: true
